Add view of publication
BIBSYSDEV/nva-data-report-api pull request #141
Opened 2024-06-18 04:27 UTC by brinxmat

In this PR:
- Simplifies data for use in graph DB. 
- Restructures data to avoid excessive nodes and removes triples not in queries
- I don't like the naming, please suggest something
- probably needs far more extensive testing, but I suggest we continue and check out a branch for testing

Next steps:
- wire the code into transformation
- fix the queries used by the APIs
- Do the same for NVI (I'm assuming that the NVI data has a simpler structure to begin with)

2024-06-18 05:22 UTC, ketilaa approved these changes
Looks good. Looking forward to see it in use. Sparql is still a bit hard to read to me. No good suggestions for naming.

2024-06-18 06:03 UTC, brinxmat commented
> Looks good. Looking forward to see it in use. Sparql is still a bit hard to read to me. No good suggestions for naming.

I updated the code with annotations to make it easier to fathom.

2024-06-18 06:13 UTC, ketilaa approved these changes

2024-06-18 13:06 UTC, truhacevkir requested changes

2024-06-18 13:06 UTC, truhacevkir commented on bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/ViewCompiler.java
> +        var query = IoUtils.stringFromResources(Path.of("view_of_publication.sparql"));
Should be constant

2024-06-18 13:06 UTC, truhacevkir commented on bulk-load/src/test/java/no/sikt/nva/data/report/api/etl/transformer/ViewCompilerTest.java
> +        assertTrue(expected().isIsomorphicWith(model));
new line?

2024-06-18 13:06 UTC, truhacevkir commented on bulk-load/src/main/resources/view_of_publication.sparql
> +}
new line?

2024-06-19 06:27 UTC, truhacevkir approved these changes

2024-06-19 06:27 UTC, monaullah commented on bulk-load/src/main/resources/view_of_publication.sparql
> +#         "id": "https://example.org/organization/201.15.1.0",
The affiliation itself needs to be repeated as the `department` property?

2024-06-19 06:28 UTC, monaullah commented on bulk-load/src/main/resources/view_of_publication.sparql
> +#       "role": {
Flatten?

2024-06-19 06:35 UTC, monaullah commented on bulk-load/src/main/resources/view_of_publication.sparql
> +      FILTER(!ISBLANK(?identity))
Move filter up

2024-06-19 06:36 UTC, monaullah commented on bulk-load/src/test/resources/journal.json
> +{
Rename files to AcademicArticle?

2024-06-19 06:51 UTC, monaullah commented on bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/ViewCompiler.java
> +package no.sikt.nva.data.report.api.etl.transformer;
Move to commoms?

2024-06-27 10:38 UTC, monaullah commented
@brinxmat approved?

2024-06-27 12:09 UTC, merged