Use document unwrapper
BIBSYSDEV/nva-data-report-api pull request #57
Opened 2024-02-14 15:32 UTC by brinxmat

- Use document unwrapper
- Get the name of the document from the id (we should likely do this everywhere…)

2024-02-14 15:41 UTC, truhacevkir commented on bulk-load/src/main/java/no/sikt/nva/data/report/api/etl/transformer/BulkTransformerHandler.java
> +    private JsonNode unwap(String json) {
unwrap

2024-02-14 15:41 UTC, truhacevkir approved these changes

2024-02-15 09:13 UTC, monaullah approved these changes

2024-02-15 09:14 UTC, merged

2024-02-15 09:15 UTC, monaullah requested changes
I think this allows you to move `IndexDocument` and `EventConsumptionAttributes` to `test` directory